[teamsyncd]: Fix LAG add: write MTU configuration
Azure/sonic-swss pull request #1423
Opened 2020-08-31 12:52 UTC by nazariig

Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

The current `apply_temp_view` logic doesn't handle MTU configuration during warm-reboot:

Before warm-reboot:
```
root@sonic:/home/admin# redis-cli -n 0 HGETALL 'LAG_TABLE:PortChannel0001'
1) "admin_status"
2) "up"
3) "oper_status"
4) "up"
5) "mtu"
6) "9100"
```

After warm-reboot:
```
root@sonic:/home/admin# redis-cli -n 0 HGETALL 'LAG_TABLE:PortChannel0001'
1) "admin_status"
2) "up"
3) "oper_status"
4) "up"
```

This ends up in traffic disruption after ISSU end:
```
Aug 31 07:57:07.043050 sonic NOTICE swss#orchagent: :- addRouterIntfs: Create router interface Ethernet116 MTU 9100
Aug 31 07:57:07.052926 sonic NOTICE swss#orchagent: :- addRouterIntfs: Create router interface PortChannel0001 MTU 1492
Aug 31 07:57:07.204451 sonic NOTICE swss#orchagent: :- addRouterIntfs: Create router interface Vlan23 MTU 9100

Aug 31 07:57:07.554444 sonic INFO syncd#supervisord: syncd Aug 31 07:57:07 NOTICE  SAI_RIF: mlnx_sai_rif.c[566]- mlnx_create_router_interface: Create rif, #0 VIRTUAL_ROUTER_ID=VIRTUAL_ROUTER,(0:0),0,0000,0 #1 SRC_MAC_ADDRESS=[50:6b:4b:96:5e:00] #2 TYPE=PORT #3 PORT_ID=PORT,(0:0),11b00,0000,0 #4 MTU=9100
Aug 31 07:57:07.573953 sonic INFO syncd#supervisord: syncd Aug 31 07:57:07 NOTICE  SAI_RIF: mlnx_sai_rif.c[566]- mlnx_create_router_interface: Create rif, #0 VIRTUAL_ROUTER_ID=VIRTUAL_ROUTER,(0:0),0,0000,0 #1 SRC_MAC_ADDRESS=[50:6b:4b:96:5e:00] #2 TYPE=PORT #3 PORT_ID=LAG,(0:0),40,0000,0 #4 MTU=1492
Aug 31 07:57:07.599988 sonic INFO syncd#supervisord: syncd Aug 31 07:57:07 NOTICE  SAI_RIF: mlnx_sai_rif.c[566]- mlnx_create_router_interface: Create rif, #0 VIRTUAL_ROUTER_ID=VIRTUAL_ROUTER,(0:0),0,0000,0 #1 SRC_MAC_ADDRESS=[50:6b:4b:96:5e:00] #2 TYPE=VLAN #3 VLAN_ID=VLAN,(0:0),17,0000,0 #4 MTU=9100

Aug 31 07:57:11.967761 sonic INFO syncd#supervisord: syncd Aug 31 07:57:11 NOTICE  SAI_UTILS: mlnx_sai_utils.c[2397]- set_dispatch_attrib_handler: Set FAST_API_ENABLE, key:Switch ID 1, val:false

Aug 31 07:57:22.013521 sonic NOTICE swss#orchagent: :- setRouterIntfsMtu: Set router interface Vlan23 MTU to 9100
Aug 31 07:57:22.016550 sonic INFO syncd#supervisord: syncd Aug 31 07:57:22 NOTICE  SAI_UTILS: mlnx_sai_utils.c[2397]- set_dispatch_attrib_handler: Set MTU, key:rif idx 3, val:9100
Aug 31 07:57:22.017188 sonic NOTICE swss#orchagent: :- setRouterIntfsMtu: Set router interface PortChannel0001 MTU to 9100
Aug 31 07:57:22.021689 sonic INFO syncd#supervisord: syncd Aug 31 07:57:22 NOTICE  SAI_UTILS: mlnx_sai_utils.c[2397]- set_dispatch_attrib_handler: Set MTU, key:rif idx 2, val:9100
```

**What I did**
* Added missing MTU filed

**Why I did it**
* To fix warm-reboot `apply_temp_view` logic

**How I verified it**
* Did warm-reboot several times with frame size equal to 9100 - no traffic disruption is observed

**Details if related**

2020-08-31 12:59 UTC, liat-grozovik approved these changes

2020-08-31 12:59 UTC, stepanblyschak approved these changes

2020-08-31 21:33 UTC, prsunny commented
This was done on purpose for a use-case where kernel mtu is different from config_db mtu - https://github.com/Azure/sonic-swss/pull/1053.

2020-09-01 04:01 UTC, liat-grozovik commented
> This was done on purpose for a use-case where kernel mtu is different from config_db mtu - #1053.

So how do you suggest to overcome this flow?
This is legal flow were warm boot is not working.

BTW why should we have MTU mismatch between kernel and config db. At some point the Linux direct command was not recommended and all should go via the config db.

2020-09-09 18:24 UTC, yxieca commented
Alibaba is ok with moving forward with closing this PR and tracking this change internally.

After merging this change, sonic will NOT support different MTU size between Kernel and ASIC.

2020-09-09 18:33 UTC, yxieca commented
Alibaba is ok with moving forward with closing this PR and tracking this change internally.

After merging this change, sonic will NOT support different MTU size between Kernel and ASIC.

This change will need to pass regular and warm reboot test.

Unit test can come with the master change. Please provide following logs with this change:

1. config reload configuration flow
2. swss restart configuration flow
3. first warm reboot configuration flow
4. subsequent warm reboot configuration flow

2020-09-09 18:33 UTC, prsunny approved these changes

2020-09-09 18:34 UTC, prsunny requested changes
Waiting for test result

2020-09-10 17:18 UTC, nazariig commented
Issue: https://github.com/Azure/sonic-swss/issues/1432

2020-09-10 17:20 UTC, nazariig commented
@prsunny done. Please check the issue.

2020-09-11 01:17 UTC, prsunny approved these changes

2020-09-11 01:57 UTC, abdosi commented
we are able to hit this issue on one of our multi-asic platforms for some of port-channels after cold-boot.
So this issue is not during warm-boot only and possible race condition can happen between teammgr and teamsync in updating LAG Table in APP DB.

@judyjoseph @prsunny

2020-09-11 01:57 UTC, merged