Vlan interface can bind vrf after set the valn interface ip.
Azure/sonic-swss pull request #1435
Opened 2020-09-14 07:42 UTC by iris00522

**What I did**
Vlan interface can bind vrf after set the valn interface ip.
I want to set SAI_ROUTER_INTERFACE_ATTR_VIRTUAL_ROUTER_ID to modify vrf of vlan intf, 
but SAI_ROUTER_INTERFACE_ATTR_VIRTUAL_ROUTER_ID attr is create only and cannot be modified.
If perfix is not null and vrf id is different then re-create vlan intf to modify vrf id of vlan intf.  
**Why I did it**
follow  the cmd,  the vrf id of the vlan interface can't be set to Vrf1.

cmd:
sudo config vlan add 2000
sudo config vlan member add 2000 Ethernet8
sudo config vrf add Vrf1
sudo config interface ip add Vlan2000 10.0.0.66/31
sudo config interface vrf bind Vlan2000 Vrf1

**How I verified it**
follow cmd to set and check syslog and check show intf setting of bcm
# syslog
Sep 14 06:33:25.236680 as7726-32x-3 INFO lldp#supervisord: lldpd 2020-09-14T06:33:25 [INFO/netlink] removal request for address of 10.0.0.66%49, but no knowledge of it
Sep 14 06:33:25.241807 sonic NOTICE swss#intfmgrd: :- doIntfGeneralTask: Vlan2000 change to Vrf1
Sep 14 06:33:25.241807 sonic NOTICE swss#orchagent: :- removeIp2MeRoute: Remove packet action trap route ip:10.0.0.66
Sep 14 06:33:25.246689 as7726-32x-3 INFO lldp#lldpd[97]: removal request for address of fe80::6a21:5fff:fe7b:636%49, but no knowledge of it
Sep 14 06:33:25.246982 as7726-32x-3 INFO lldp#supervisord: lldpd 2020-09-14T06:33:25 [INFO/netlink] removal request for address of fe80::6a21:5fff:fe7b:636%49, but no knowledge of it
Sep 14 06:33:25.248272 as7726-32x-3 NOTICE iccpd#iccpd: [iccp_event_handler_obj_input_newlink.NOTICE] Update local port Vlan2000 state down
Sep 14 06:33:25.257121 as7726-32x-3 NOTICE iccpd#iccpd: [iccp_event_handler_obj_input_newlink.NOTICE] Update local port Vlan2000 state up
Sep 14 06:33:25.260402 sonic NOTICE swss#orchagent: :- removeRouterIntfs: Remove router interface for port Vlan2000
Sep 14 06:33:25.260504 as7726-32x-3 INFO syncd#syncd: message repeated 12 times: [ [none] _brcm_sai_fdb_event_cb:180 move event fdb count global data not change]
Sep 14 06:33:25.260504 as7726-32x-3 NOTICE syncd#syncd: :- removeRif: Trying to remove nonexisting router interface counter from Id 0x60000000006bb
Sep 14 06:33:25.260594 sonic NOTICE swss#orchagent: :- addRouterIntfs: Create router interface Vlan2000 MTU 9100

# l3 intf show
l3 intf show
Free L3INTF entries: 16370
Unit  Intf  VRF Group VLAN    Source Mac     MTU TTL Tunnel InnerVlan  NATRealm
0     4096  0     0     1    68:21:5f:7b:06:36  9100 0    0     0     0
0     4097  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4098  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4099  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4100  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4101  0     0     1000 68:21:5f:7b:06:36  9100 0    0     0     0
0     4102  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4103  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4104  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4105  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4106  0     0     4095 68:21:5f:7b:06:36  9100 0    0     0     0
0     4107  1     0     2000 68:21:5f:7b:06:36  9100 0    0     0     0

2020-09-14 23:26 UTC, prsunny commented
@iris00522 , this is an intentional dependency that was made during the VRF design. You can refer this [section ](https://github.com/Azure/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md#add-vrf-binding-information-in-config_dbjson-file) of VRF HLD. We don't want to allow changing VRFs (in this case from default to non-default) without cleanup.

2020-09-14 23:27 UTC, prsunny requested changes
As comment

2020-09-15 06:47 UTC, iris00522 commented
@prsunny ok, I see, thanks.
I have the other question, could I add error message to sonic-utilities when vrf bind to interface after add ip to interface.

2020-09-15 20:34 UTC, prsunny commented
I'm fine with having the check in sonic-utilities. @shine4chen , @tylerlinp  what do you think?

2020-09-16 00:46 UTC, gord1306 commented
> I'm fine with having the check in sonic-utilities. @shine4chen , @tylerlinp what do you think?

if sonic-utilities have this check, does it mean sonic-mgmt-framework also need to add this check?

2020-09-17 02:17 UTC, shine4chen commented
> I'm fine with having the check in sonic-utilities. @shine4chen , @tylerlinp what do you think?

It is a bug in vrf bind CLI. We will submit a PR to resolve it.
In fact vrf-bind CLI combines the following steps:
- if interface has ip addresses, flush them
- remove interface from configdb and check statedb to make sure it done
- recreate interface with new vrf.

It is user friendly. I don't think we should add extra check logic. The root cause of bug is that we change vrf state-db schema but don't sync it on sonic-utils code.

2020-09-17 04:39 UTC, tylerlinp commented
As @prsunny said, in our design changing VRFs was not supported, in orch there may be more changes needed than this PR done to support it.
The right config sequence is that bind vrf first and then set ip address. For backward compatiblity, in setting ip command add an interface key implicitly.
I submited a PR [sonic-utilities#1119](https://github.com/Azure/sonic-utilities/pull/1119) to fix the bug @shine4chen mentioned.

2021-03-18 06:10 UTC, closed without merging