Check for string length before calling substr
Azure/sonic-swss pull request #1456
Opened 2020-10-01 22:45 UTC by smaheshm

**What I did**
Check for string length before calling sustring with a specific length.

**Why I did it**

For unsupported DROP counters the string returned is the enum value as a string, whose max length is 2. 
Calling a substring with a length greater than 2 was crashing syncd.

**How I verified it**

Verified syncd doesn't crash after the fix.

**Details if related**

Oct  1 16:07:39.387872 str-s6000-acs-9 INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::out_of_range'
Oct  1 16:07:39.387872 str-s6000-acs-9 INFO swss#supervisord: orchagent   what():  basic_string::substr: __pos (which is 19) > this->size() (which is 2)

2020-10-01 23:16 UTC, daall commented
>For unsupported DROP counters the string returned is the enum value as a string, whose max length is 2. Calling a substring with a length greater than 2 was crashing syncd.

@smaheshm is this something new in 4.2?

2020-10-01 23:17 UTC, daall requested changes

2020-10-01 23:17 UTC, daall commented on orchagent/debug_counter/drop_counter.cpp
> +            if (drop_reason.length() < INGRESS_DROP_REASON_PREFIX_LENGTH)
```suggestion
            if (drop_reason.length() < EGRESS_DROP_REASON_PREFIX_LENGTH)
```

2020-10-01 23:21 UTC, smaheshm commented on orchagent/debug_counter/drop_counter.cpp
> +            if (drop_reason.length() < INGRESS_DROP_REASON_PREFIX_LENGTH)
:grimacing:

2020-10-01 23:26 UTC, smaheshm commented
> > For unsupported DROP counters the string returned is the enum value as a string, whose max length is 2. Calling a substring with a length greater than 2 was crashing syncd.
> 
> @smaheshm is this something new in 4.2?

SDK seems to be a bit ahead w.r.t. SAI. We also need to update SAI and SAIREDIS. In any case we should have this check to avoid crash.

2020-10-01 23:26 UTC, daall approved these changes

2020-10-01 23:27 UTC, daall commented
> > > For unsupported DROP counters the string returned is the enum value as a string, whose max length is 2. Calling a substring with a length greater than 2 was crashing syncd.
> > 
> > 
> > @smaheshm is this something new in 4.2?
> 
> SDK seems to be a bit ahead w.r.t. SAI. We also need to update SAI and SAIREDIS. In any case we should have this check to avoid crash.

Agreed! Thanks for catching this! :smile:

2020-10-02 14:21 UTC, kcudnik approved these changes

2020-10-02 15:10 UTC, smaheshm commented
retest vs please

2020-10-02 15:11 UTC, smaheshm commented
retest this please

2020-10-02 18:15 UTC, merged