Add diagnose option "-Wno-stringop-overflow" option to avoid the compiling errors in order to avoid error in gcc9
Azure/sonic-swss pull request #1621
Opened 2021-02-02 12:24 UTC by stephenxs

Add "-Wno-stringop-overflow" option to avoid the following error:
```
    orch.cpp: In member function 'ref_resolve_status Orch::resolveFieldRefArray(type_map&, const string&, swss::KeyOpFieldsValuesTuple&, std::vector<long unsigned int>&, std::string&)':
    orch.cpp:609:41: error: 'strlen' argument missing terminating nul [-Werror=stringop-overflow=]
      609 |                     object_name_list += string(&list_item_delimiter);
          |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from orch.cpp:6:
    orch.h:25:12: note: referenced argument declared here
       25 | const char list_item_delimiter = ',';
          |            ^~~~~~~~~~~~~~~~~~~
    cc1plus: all warnings being treated as errors
```
According to [GCC 9: special_values_formatter.hpp:43:16: error: 'strlen' argument missing terminating nul #29](https://github.com/CauldronDevelopmentLLC/cbang/issues/29), this is an error from boost and can be suppressed by using this option

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

2021-02-02 19:51 UTC, qiluo-msft commented
It seems compiler report a true code bug.
```c++
const char list_item_delimiter = ',';
object_name_list += string(&list_item_delimiter)
```

Could you check why you feed a non zero-terminated char* to string ctor?

2021-02-02 19:51 UTC, qiluo-msft requested changes
As comment

2021-02-03 00:55 UTC, stephenxs commented
> It seems compiler report a true code bug.
> 
> ```c++
> const char list_item_delimiter = ',';
> object_name_list += string(&list_item_delimiter)
> ```
> 
> Could you check why you feed a non zero-terminated char* to string ctor?

```c++
const char list_item_delimiter = ',';
object_name_list += string(&list_item_delimiter, 1);
```
Need to add a `count `
Meanwhile, I don’t quite understand why it was not catched by gcc8

2021-02-03 01:24 UTC, qiluo-msft commented
This bug should be detected by either compiler or linter. Could you help explore a general solution to detect other unfound or future occurrences, during build process?

2021-02-03 09:07 UTC, kcudnik commented
change PR name to fix gcc9 warning

2021-02-03 09:11 UTC, stephenxs commented
> change PR name to fix gcc9 warning

Done.

2021-02-03 09:15 UTC, kcudnik commented
> This bug should be detected by either compiler or linter. Could you help explore a general solution to detect other unfound or future occurrences, during build process?

i actually checked g++ without and with O2 optimization, and if you use & on char constant, it puts data as a single character string which is padded by zeros, and with O2 even aligned with 0x10, but it could be just good practice by gcc, it may not be guaranteed, so warning is helpful in that case

2021-02-03 18:52 UTC, qiluo-msft commented on orchagent/orch.cpp
> +                    object_name_list += string(&list_item_delimiter, 1);
```suggestion
                    object_name_list += list_item_delimiter;
```

2021-02-04 05:13 UTC, stephenxs commented on orchagent/orch.cpp
> +                    object_name_list += string(&list_item_delimiter, 1);
It works. Done.

2021-02-04 05:56 UTC, stephenxs commented
> > This bug should be detected by either compiler or linter. Could you help explore a general solution to detect other unfound or future occurrences, during build process?
> 
> i actually checked g++ without and with O2 optimization, and if you use & on char constant, it puts data as a single character string which is padded by zeros, and with O2 even aligned with 0x10, but it could be just good practice by gcc, it may not be guaranteed, so warning is helpful in that case

I'm not sure whether it's related to optimization. I think the default alignment of the types whose size is less than a word length will be the word length of the machine, unless preprecess instructions like `#progma pack(1)` is used. This means there will be padding bytes after a char variable. But there isn't guarantee that the padding bytes will be zero.

2021-02-04 06:01 UTC, qiluo-msft approved these changes

2021-02-06 08:33 UTC, kcudnik approved these changes

2021-02-06 08:35 UTC, merged