patch for issue #1971 - enable Rx Drop handling for cisco-8000
Azure/sonic-swss pull request #2041
Opened 2021-11-21 23:50 UTC by alpeshspatel

Signed-off-by: Alpesh S Patel <alpesh@cisco.com>

**What I did**

1. Enables support for Rx traffic drop for a port/tc by applying the zero buffer profile
2. Changed class hierarchy so that default getHwCounters() function is used (since the Rx counter support is enabled)
3. Fixes a pfc-wd off by 1 detection in case of PFC-WD detection without traffic

**Why I did it**
1. enabling a missing functionality
2. leveraging sonic code as our sdk now implements the missing counter
3. fixes a bug 

**How I verified it**
on a cisco-8000 router:
1. detected pfc-wd detection and restore happens within the (detection/restore-time + 1 poll interval) duration and that the changeset passes MSFT tests
2. Verified that when PFC-WD is detected, both Rx and Tx traffic for a port/tc is dropped and no forwarding happens

**Details if related**

this patch will need to be double committed to the 202012 branch along with #1942 , #1748 and #1962

2021-11-21 23:52 UTC, alpeshspatel commented
@prsunny Can you go ahead and put me as Assignee (I cannot edit it)

2021-11-22 20:45 UTC, neethajohn commented on orchagent/pfc_restore_cisco-8000.lua
> +            if time_left <= poll_time then
We had this discussion during #1748 review. https://github.com/Azure/sonic-swss/pull/1748#discussion_r695934838
What has changed now?

2021-12-01 01:55 UTC, neethajohn commented on orchagent/pfc_restore_cisco-8000.lua
> +            if time_left <= poll_time then
@alpeshspatel , I am not clear why this is changed to compare with poll_time. in 1748, the change was made to compare with 0 and you had provided a small writeup for the reason.

2021-12-14 18:18 UTC, neethajohn requested changes

2021-12-14 18:18 UTC, neethajohn commented on orchagent/pfcactionhandler.cpp
> +    string platform(getenv("platform"));
assign to empty string if "platform" does not exist

2021-12-14 18:18 UTC, neethajohn commented on orchagent/pfcactionhandler.cpp
> +    string platform(getenv("platform"));
assign to empty string if "platform" does not exist

2021-12-14 18:19 UTC, neethajohn commented on orchagent/pfc_restore_cisco-8000.lua
> +            if time_left <= poll_time then
resolved offline

2021-12-14 23:36 UTC, alpeshspatel commented
@neethajohn : just pushed a change and marked the two comments as resolved for the time being. Please re-review and advise on next steps.

2021-12-15 01:20 UTC, neethajohn commented on orchagent/pfcactionhandler.cpp
> +    if (env_plat == nullptr)
string platform = getenv("platform") ? getenv("platform") : ""  would be much cleaner

2021-12-15 01:46 UTC, sachinv-msft commented
@neethajohn could you please review this PR?

2021-12-15 17:18 UTC, neethajohn approved these changes

2021-12-16 15:22 UTC, alpeshspatel commented
@prsunny 
What would be the next steps on this?

2021-12-17 01:08 UTC, merged