set remote vtep the netdev down before delete.
Azure/sonic-swss pull request #2075
Opened 2021-12-09 08:49 UTC by iris00522

**What I did**
set vtep-xxx the netdev down before delete vtep-xxx .
**Why I did it**
the vxlan netdev will be only delete only when remove vxlan tunnel map,
but the FRR doesn't remove IMET route entirely after receiving the delete event.
Therefore, add to set netdev down before delete the netdev to trigger FRR to remove related IMET route.

**How I verified it**
using t0 topology config
and flow the cmmand

redis-cli -n 4 -c DEL "VLAN_MEMBER|Vlan1000|Ethernet4"
sudo config interface ip add Ethernet4 10.0.0.64/31
vtysh
configure
ip route 100.0.0.65/31 10.0.0.65
exit
exit

sudo config vxlan add vtep 10.1.0.32
sudo config vxlan evpn_nvo add evpnnvo1 vtep
sudo config vxlan map add vtep 1000 10000

vtysh
configure
router bgp 65100
neighbor 10.0.0.65 remote-as 65200
address-family l2vpn evpn
neighbor 10.0.0.65 activate
advertise-all-vni
exit
exit
exit
exit

neighbor:
setting bgp and type 3 and typ2 packet 

**Details if related**

2021-12-09 18:44 UTC, prsunny commented
@srj102 , @dgsudharsan for review

2021-12-10 02:29 UTC, link19430 commented
/azpw run

2022-01-26 22:55 UTC, dgsudharsan requested changes

2022-01-26 22:55 UTC, dgsudharsan commented on cfgmgr/vxlanmgr.cpp
> +static int cmdDownVxlan(const swss::VxlanMgr::VxlanInfo & info, std::string & res)
This comes in VNET flow and not in regular EVPN flow. Is it needed?

2022-01-26 22:55 UTC, dgsudharsan commented on cfgmgr/vxlanmgr.cpp
> +static int cmdDownVxlanIf(const swss::VxlanMgr::VxlanInfo & info, std::string & res)
Same as above. These APIs are called only for VNET table. Are these changes needed?

2022-01-26 22:56 UTC, dgsudharsan commented
There are some APIs which are in VNET flow that are changed. These may not be related to EVPN flow the issue is reported. Should we change? @prsunny 
@srj102  Can you also please review?

2022-01-27 00:51 UTC, prsunny commented
> There are some APIs which are in VNET flow that are changed. These may not be related to EVPN flow the issue is reported. Should we change? @prsunny @srj102 Can you also please review?

Agree with @dgsudharsan , this doesn't fall into the EVPN flow. Can you please check what's intended?

2022-02-28 18:54 UTC, dgsudharsan approved these changes

2022-02-28 19:19 UTC, prsunny commented
/azp run

2022-03-22 22:28 UTC, prsunny commented
/azp run

2022-04-08 18:09 UTC, dgsudharsan commented
@iris00522 Can you please sync your changes to latest master?

2022-04-11 07:16 UTC, iris00522 commented
@dgsudharsan @prsunny  help to review again, thank you.

2022-04-11 21:23 UTC, prsunny commented
/azp run

2022-04-21 02:11 UTC, gord1306 commented
@dgsudharsan @prsunny can this PR be merged? Thanks

2022-04-21 21:21 UTC, prsunny commented
/azp run

2022-04-25 20:59 UTC, prsunny commented
@dgsudharsan , can you please signoff?

2022-04-26 01:10 UTC, dgsudharsan approved these changes

2022-04-26 01:12 UTC, prsunny approved these changes

2022-04-26 01:12 UTC, merged