[mirrororch]: Implement HW resources availability validation
Azure/sonic-swss pull request #2187
Opened 2022-03-17 16:07 UTC by nazariig

Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

**What I did**
* Added a validation to prevent mirror session configuration if there is no available HW resources

**Why I did it**
* To prevent system from unexpected reboots
* To add some debuggability information to the system journal

**How I verified it**
1. Configure mirror sessions
```bash
config mirror_session span add TEST1 Ethernet0 Ethernet4
config mirror_session span add TEST2 Ethernet8 Ethernet12
config mirror_session span add TEST3 Ethernet16 Ethernet20
config mirror_session span add TEST4 Ethernet24 Ethernet28
config mirror_session span add TEST5 Ethernet32 Ethernet36
config mirror_session span add TEST6 Ethernet40 Ethernet44
config mirror_session span add TEST7 Ethernet48 Ethernet52
config mirror_session span add TEST8 Ethernet56 Ethernet60
```

**Details if related**
* CLI
```bash
root@sonic:/home/admin# show mirror_session
ERSPAN Sessions
Name    Status    SRC IP    DST IP    GRE    DSCP    TTL    Queue    Policer    Monitor Port    SRC Port    Direction
------  --------  --------  --------  -----  ------  -----  -------  ---------  --------------  ----------  -----------

SPAN Sessions
Name    Status    DST Port    SRC Port    Direction    Queue    Policer
------  --------  ----------  ----------  -----------  -------  ---------
TEST1   active    Ethernet0   Ethernet4   both
TEST2   active    Ethernet8   Ethernet12  both
TEST3   active    Ethernet16  Ethernet20  both
TEST4   active    Ethernet24  Ethernet28  both
TEST5   active    Ethernet32  Ethernet36  both
TEST6   active    Ethernet40  Ethernet44  both
TEST7   active    Ethernet48  Ethernet52  both
TEST8   error     Ethernet56  Ethernet60  both
```

* Log
```bash
Mar 16 10:05:26.236210 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[221]- sai_object_type_get_availability: Querying SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list
Mar 16 10:05:26.236478 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[242]- sai_object_type_get_availability: Got SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list: 7
Mar 16 10:05:26.238214 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2191]- mlnx_check_mirror_attribute_on_create: Create mirror, #0 MONITOR_PORT=PORT,(0:0),10069,0000,0 #1 TYPE=LOCAL
Mar 16 10:05:26.241129 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2808]- mlnx_create_mirror_session: Created sdk mirror obj id: 1
Mar 16 10:05:26.241222 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2847]- mlnx_create_mirror_session: Created SAI mirror obj id: 10000000e
Mar 16 10:05:26.242355 sonic NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set INGRESS_MIRROR_SESSION, key:port 1006a, val:1 : [ 10000000e]
Mar 16 10:05:26.243616 sonic NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set EGRESS_MIRROR_SESSION, key:port 1006a, val:1 : [ 10000000e]
Mar 16 10:05:26.244686 sonic NOTICE swss#orchagent: :- activateSession: Activated mirror session TEST1
Mar 16 10:05:26.244686 sonic NOTICE swss#orchagent: :- createEntry: Created mirror session TEST1
Mar 16 10:05:26.732414 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[221]- sai_object_type_get_availability: Querying SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list
Mar 16 10:05:26.733007 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[242]- sai_object_type_get_availability: Got SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list: 6
Mar 16 10:05:26.734711 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2191]- mlnx_check_mirror_attribute_on_create: Create mirror, #0 MONITOR_PORT=PORT,(0:0),10031,0000,0 #1 TYPE=LOCAL
Mar 16 10:05:26.736280 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2808]- mlnx_create_mirror_session: Created sdk mirror obj id: 2
Mar 16 10:05:26.736395 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2847]- mlnx_create_mirror_session: Created SAI mirror obj id: 20000000e
Mar 16 10:05:26.738465 sonic NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set INGRESS_MIRROR_SESSION, key:port 10071, val:1 : [ 20000000e]
Mar 16 10:05:26.740891 sonic NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set EGRESS_MIRROR_SESSION, key:port 10071, val:1 : [ 20000000e]
Mar 16 10:05:26.742509 sonic NOTICE swss#orchagent: :- activateSession: Activated mirror session TEST2
Mar 16 10:05:26.742509 sonic NOTICE swss#orchagent: :- createEntry: Created mirror session TEST2
Mar 16 10:05:27.270144 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[221]- sai_object_type_get_availability: Querying SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list
Mar 16 10:05:27.270256 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[242]- sai_object_type_get_availability: Got SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list: 5
Mar 16 10:05:27.271919 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2191]- mlnx_check_mirror_attribute_on_create: Create mirror, #0 MONITOR_PORT=PORT,(0:0),10072,0000,0 #1 TYPE=LOCAL
Mar 16 10:05:27.272975 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2808]- mlnx_create_mirror_session: Created sdk mirror obj id: 3
Mar 16 10:05:27.272975 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2847]- mlnx_create_mirror_session: Created SAI mirror obj id: 30000000e
Mar 16 10:05:27.274545 sonic NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set INGRESS_MIRROR_SESSION, key:port 10032, val:1 : [ 30000000e]
Mar 16 10:05:27.276311 sonic NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set EGRESS_MIRROR_SESSION, key:port 10032, val:1 : [ 30000000e]
Mar 16 10:05:27.277404 sonic NOTICE swss#orchagent: :- activateSession: Activated mirror session TEST3
Mar 16 10:05:27.277404 sonic NOTICE swss#orchagent: :- createEntry: Created mirror session TEST3
Mar 16 10:05:27.745178 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[221]- sai_object_type_get_availability: Querying SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list
Mar 16 10:05:27.745329 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[242]- sai_object_type_get_availability: Got SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list: 4
Mar 16 10:05:27.746975 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2191]- mlnx_check_mirror_attribute_on_create: Create mirror, #0 MONITOR_PORT=PORT,(0:0),10073,0000,0 #1 TYPE=LOCAL
Mar 16 10:05:27.748498 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2808]- mlnx_create_mirror_session: Created sdk mirror obj id: 4
Mar 16 10:05:27.748498 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2847]- mlnx_create_mirror_session: Created SAI mirror obj id: 40000000e
Mar 16 10:05:27.750200 sonic NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set INGRESS_MIRROR_SESSION, key:port 10074, val:1 : [ 40000000e]
Mar 16 10:05:27.752326 sonic NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[1833]- set_dispatch_attrib_handler: Set EGRESS_MIRROR_SESSION, key:port 10074, val:1 : [ 40000000e]
Mar 16 10:05:27.754113 sonic NOTICE swss#orchagent: :- activateSession: Activated mirror session TEST4
Mar 16 10:05:27.754113 sonic NOTICE swss#orchagent: :- createEntry: Created mirror session TEST4
Mar 16 10:05:28.245222 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[221]- sai_object_type_get_availability: Querying SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list
Mar 16 10:05:28.245222 sonic NOTICE syncd#SDK: [SAI_OBJECT.NOTICE] mlnx_sai_object.c[242]- sai_object_type_get_availability: Got SAI_OBJECT_TYPE_MIRROR_SESSION availability, empty list: 3
Mar 16 10:05:28.246993 sonic NOTICE syncd#SDK: [SAI_MIRROR.NOTICE] mlnx_sai_mirror.c[2191]- mlnx_check [...]

2022-03-20 08:59 UTC, liat-grozovik requested changes
Missing test to cover the new code and the failures in case of no new resources.
The warning of not supported resource availability will happen each time we would try to create one. Should we found a way to have it only once and in all other cases just return true?

2022-03-21 10:41 UTC, nazariig commented
> Missing test to cover the new code and the failures in case of no new resources. The warning of not supported resource availability will happen each time we would try to create one. Should we found a way to have it only once and in all other cases just return true?

@liat-grozovik unfortunately we don't have an infra for that - there is no way to dynamically set resource limit per test case, `libsaivs` allows only to hardcode it. On SONiC platforms which doesn't support resource availability check there is no way to avoid it using only SAI API. We can consider some kind of cache to read only once, but the question is: does't it worth these efforts and what is the benefit?

2022-03-22 16:56 UTC, liat-grozovik commented
/azp run Azure.sonic-swss

2022-03-27 06:27 UTC, liat-grozovik approved these changes

2022-03-27 06:27 UTC, liat-grozovik commented
@prsunny could you please help to review?

2022-03-30 22:53 UTC, prsunny approved these changes
change lgtm. @bingwang-ms , can you take a look?

2022-04-04 13:22 UTC, merged