Initialize P4 code only when running on a P4 platform
Azure/sonic-swss pull request #2257
Opened 2022-05-06 01:52 UTC by saiarcot895

Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

**What I did**

The P4Orch initializer assumes that UDF is available on the platform,
which may or may not be true. Initialize P4 only when running on a P4
platform.

**Why I did it**

On some platforms (such as Broadcom), UDF is not available, and trying to program it results in an error. This doesn't break anything during coldboot, but fails warmboot.

**How I verified it**

Tested on virtual switch, Broadcom test is pending.

**Details if related**

2022-05-06 23:02 UTC, saiarcot895 commented
@donNewtonAlpha FYI

2022-05-09 19:13 UTC, saiarcot895 commented
/azp run

2022-05-09 23:04 UTC, prsunny commented on orchagent/orchdaemon.cpp
> +    if (platform == P4_PLATFORM_SUBSTRING) {
Please move `{` to new line.

2022-05-10 00:08 UTC, saiarcot895 commented on orchagent/orchdaemon.cpp
> +    if (platform == P4_PLATFORM_SUBSTRING) {
Done.

2022-05-12 19:20 UTC, baxia-lan commented
Hi @saiarcot895, could you please attach the details about the issues that you are seeing when init p4orch during warmreboot on broadcom?

2022-05-12 19:20 UTC, baxia-lan commented on orchagent/orchdaemon.cpp
> +    if (platform == P4_PLATFORM_SUBSTRING)
The p4orch should be able to initialized successfully on platform=broadcom switches. And the default UDF match created in p4orch during init is calling standard SAI API(https://github.com/Azure/sonic-swss/blob/eff725ff1803f7e4948a25e53abc68886e43b367/orchagent/p4orch/acl_table_manager.cpp#L40)

2022-05-12 19:25 UTC, saiarcot895 commented
Azure/sonic-buildimage#10410 has more details on this, but it appears that the Broadcom SAI library doesn't support UDF. During coldboot, there's an error message, but it's not treated as a fatal error. During warmboot, however, failing an ASIC operation is considered a fatal error.

2022-05-12 22:22 UTC, bocon13 requested changes
Thanks for the PR, @saiarcot895

I understand you are having trouble with warm-boot and we should work with you on this.

The `p4` platform isn't related to the P4Orch; that target is an older software switch. The P4Orch is designed for many different platforms, including Broadcom.

cc: @mint570

2022-05-17 19:48 UTC, saiarcot895 commented
Hi @bocon13, I've changed the conditional check to not initialize if running on a Broadcom platform. This will keep it available on other platforms.

Would this change be fine?

2022-05-18 05:11 UTC, bocon13 commented
Hi @saiarcot895, the Broadcom platform is one of our main platforms that we aim to support with the P4Orch.

Can you provide some error logs (or excerpts) that we can take a look at? It would be good to work together to address the underlying issue.

2022-05-18 06:32 UTC, saiarcot895 commented
Azure/sonic-buildimage#10410 has some output from syslog. Is there something more specific that you need?

2022-05-18 16:14 UTC, mint570 commented
I believe we can do the UDF match initialization in the first entry instead of in the constructor.
This should address this particular issue.

(However, p4orch does not support warmboot yet. So warmboot will not work if we have programmed some P4RT tables. But it should work with the fix if there is no P4RT table.)

@baxia-lan, what do you think?

2022-05-20 01:27 UTC, saiarcot895 commented
@baxia-lan meaning it would still do the UDF match initialization on warm reboot, even though nothing may be using it?

2022-05-20 01:32 UTC, baxia-lan commented
@saiarcot895  no, only if there is a ACL table created with UDF fields via p4orch, the UDF match creation will be called. I am preparing https://github.com/Azure/sonic-swss/pull/2282 to address this issue. Working on test coverage now

2022-05-25 01:11 UTC, saiarcot895 commented
Closing in favor of #2282.

2022-05-25 01:11 UTC, closed without merging