[muxorch] Always use direct link for SoC IPs
Azure/sonic-swss pull request #2369
Opened 2022-07-05 13:59 UTC by lolyu

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

2022-07-06 00:10 UTC, prsunny requested changes
I prefer to take a different approach for this and not make it part of the nbr_handler

2022-07-06 00:52 UTC, lolyu commented
> I prefer to take a different approach for this and not make it part of the nbr_handler. We can just return from the 'update' function.

OK, I will change it to simply skip the neighbor handler

2022-07-08 19:32 UTC, prsunny commented
Propose to have it as below:

1. Extend Muxcable class to have a list of soc_ip4/6 addresses. Name it say, 'skip_neighbor_list'
2. In MuxOrch::updateNeighbor, check for this list and return if new neighbor is present in the 'add' case.
3. No changes to MuxNeighbor class

2022-07-10 16:49 UTC, prsunny commented on orchagent/muxorch.cpp
> +    if (add && skip_neighbors_.count(nh.ip_address) != 0)
Please use find instead of count as the intend is to check if the key exists. This is the current pattern in the file.

2022-07-10 16:49 UTC, prsunny commented on orchagent/muxorch.cpp
> +        SWSS_LOG_NOTICE("Skip update neighbor %s on %s", nh.ip_address.to_string().c_str(), nh.alias.c_str());
Please move to INFO level. We don't want this to be printed for each time a neighbor update happens for the skip neighbors

2022-07-10 16:49 UTC, prsunny commented on orchagent/muxorch.cpp
> +    std::string cable_type = "active-standby";
We don't have to check for cable_type in orchagent. If 'soc_ipv4' is present, it must be skipped from tunnel neighbors. Please remove.

2022-07-10 16:51 UTC, prsunny commented
@lolyu , please dont force-push. I would like to review incremental changes.

2022-07-11 04:58 UTC, lolyu commented
> @lolyu , please dont force-push. I would like to review incremental changes.

@prsunny Sure, updated, thanks!

2022-07-13 18:17 UTC, prsunny reviewed
lgtm, minor comments

2022-07-13 18:17 UTC, prsunny commented on orchagent/muxorch.cpp
> +    if (add && skip_neighbors_.find(nh.ip_address) != skip_neighbors_.end())
Can you check if a 'del' operation does not impact the code flow?

2022-07-14 01:40 UTC, prsunny commented on tests/test_mux.py
> +        self.check_tnl_nexthop_in_asic_db(asicdb, 4)
Discussed offline with @lolyu , and it is as per the current test expectation.

2022-07-14 01:40 UTC, prsunny approved these changes

2022-07-14 13:22 UTC, merged